#! /bin/bash
set -eu

jq -r '[(.ts|tonumber),.ip,.iso3166,.asn]|@csv' |
	psql \
		-c "CREATE TEMP TABLE hostile_import (LIKE hostile);" \
		-c "\copy hostile_import (ts, ip, cc, asn) FROM stdin WITH (FORMAT csv);" \
		-c "INSERT INTO hostile (ts, ip, cc, asn) SELECT ts, ip, cc, asn FROM hostile_import ON CONFLICT DO NOTHING;"
