#! /bin/bash
set -eu
cat <<EOF
# Top 20 Hostile Countries in Germany

| Rank | Country | Total | Percent |
| ---: | :------ | ----: | ------: |
EOF
jq -r '"| \(.rank) | \(.country) | \(.attacks) | \(.percent) |"'
